"""Choose which copy of a duplicate group is kept — deterministically."""

from __future__ import annotations

from dataclasses import dataclass
from typing import TYPE_CHECKING

from media_dedup.constants import KeepReason
from media_dedup.paths.host_paths import is_within
from media_dedup.plan.copy_names import looks_like_copy
from media_dedup.plan.models import KeepDecision
from media_dedup.plan.name_rules import DEFAULT_NAME_RULES, NameRules

if TYPE_CHECKING:
    from pathlib import Path

    from media_dedup.scan.models import DuplicateGroup, MediaFile

type _SortKey = tuple[bool, int, bool, bool, bool, int, int, str]


@dataclass(frozen=True, slots=True)
class KeepPolicy:
    """How to choose the copy to keep.

    Container paths of the preferred (ordered) and protected folders, and the names
    that say nothing (generated by a camera or an app, generic folders).
    """

    preferred: tuple[Path, ...] = ()
    protected: tuple[Path, ...] = ()
    names: NameRules = DEFAULT_NAME_RULES

    def is_protected(self, file: MediaFile) -> bool:
        """Tell whether a file lies in a protected folder.

        Args:
            file: Candidate file.

        Returns:
            True when it must never be modified.
        """
        return any(is_within(file.path, folder) for folder in self.protected)

    def rank(self, file: MediaFile) -> _SortKey:
        """Sort key: the smallest key is the copy to keep.

        Order: protected folder, preferred folder (in the configured order), a name
        that does not look like a copy, a name someone chose (not generated by a camera
        or an app), a folder someone named, the oldest modification time, the shortest
        path, then alphabetical order (case-insensitive) as the final tie-breaker. The
        order follows `KeepReason`.

        Args:
            file: Candidate file.

        Returns:
            Its sort key.
        """
        preference = next(
            (
                index
                for index, folder in enumerate(self.preferred)
                if is_within(file.path, folder)
            ),
            len(self.preferred),
        )
        return (
            not self.is_protected(file),
            preference,
            looks_like_copy(file.path),
            self.names.has_generated_name(file.path),
            self.names.in_generic_folder(file.path),
            file.mtime_ns,
            len(file.path.parts),
            str(file.path).casefold(),
        )

    def decide(self, group: DuplicateGroup) -> KeepDecision:
        """Split a duplicate group into the keeper, removable and protected copies.

        Args:
            group: Identical files.

        Returns:
            The decision; protected copies other than the keeper are never removable.
        """
        ordered = sorted(group.files, key=self.rank)
        keeper, others = ordered[0], ordered[1:]
        return KeepDecision(
            digest=group.digest,
            size=group.size,
            keeper=keeper,
            removable=tuple(file for file in others if not self.is_protected(file)),
            protected=tuple(file for file in others if self.is_protected(file)),
            reason=self._reason(keeper, others[0]),
        )

    def _reason(self, keeper: MediaFile, runner_up: MediaFile) -> KeepReason:
        """Name the first criterion that ranks the keeper before the next copy.

        Args:
            keeper: The copy kept.
            runner_up: The copy ranked right after it.

        Returns:
            The decisive criterion.
        """
        criteria = zip(self.rank(keeper), self.rank(runner_up), strict=True)
        decisive = next(
            (index for index, (kept, other) in enumerate(criteria) if kept != other),
            len(KeepReason) - 1,
        )
        return list(KeepReason)[decisive]
