"""Say, in plain words, why the kept copy was chosen: a visible reason builds trust."""

from __future__ import annotations

from media_dedup.constants import KeepReason
from media_dedup.i18n import _


def keep_reason_label(reason: KeepReason | None) -> str:
    """Translate the decisive criterion of a keep decision.

    Args:
        reason: The criterion, or None when unknown.

    Returns:
        A short phrase that completes "kept because of …", or an empty string.
    """
    if reason is None:
        return ""
    labels = {
        KeepReason.PROTECTED: _("protected folder"),
        KeepReason.PREFERRED: _("preferred folder"),
        KeepReason.NOT_A_COPY: _("the other name looks like a copy"),
        KeepReason.MEANINGFUL_NAME: _(
            "a name someone chose (the other one was generated by a camera or an app)"
        ),
        KeepReason.MEANINGFUL_FOLDER: _(
            "a folder someone named (the other one is generic)"
        ),
        KeepReason.OLDEST: _("the oldest date"),
        KeepReason.SHORTEST_PATH: _("the shortest path"),
        KeepReason.ALPHABETICAL: _("alphabetical order (nothing else differs)"),
    }
    return labels[reason]
